#!/usr/bin/env bash
set -eou pipefail

# Brave Origin Update Script
# Following standard patterns for the custom-packages-flake
# Specialized for x86_64-linux only

PACKAGE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PACKAGE_FILE="$PACKAGE_DIR/default.nix"

# Get current version
CURRENT_VERSION=$(grep -oP 'version\s*=\s*"\K[^"]+' "$PACKAGE_FILE" || echo "0.0.0")
echo "Current version: $CURRENT_VERSION"

echo "Fetching releases from GitHub API..."
RELEASES=$(gh api repos/brave/brave-browser/releases?per_page=20)

# Find the latest prerelease that has brave-origin-nightly x86_64-linux asset
RELEASE_JSON=$(echo "$RELEASES" | jq -c '
  map(
    select(.prerelease)
    | .tag_name as $tag
    | ($tag | ltrimstr("v")) as $ver
    | .assets as $assets
    | select(
        any($assets[]?.name; . == ("brave-origin-nightly_" + $ver + "_amd64.deb"))
      )
  )
  | first
')

if [ -z "$RELEASE_JSON" ] || [ "$RELEASE_JSON" == "null" ]; then
    echo "Could not find a suitable Brave Origin release."
    exit 1
fi

LATEST_TAG=$(echo "$RELEASE_JSON" | jq -r '.tag_name')
LATEST_VERSION=$(echo "$LATEST_TAG" | sed 's/^v//')

echo "Latest version: $LATEST_VERSION"

if [ "$CURRENT_VERSION" = "$LATEST_VERSION" ]; then
    echo "Brave Origin is up-to-date."
    if [ -n "${GITHUB_ENV:-}" ]; then
        echo "UPDATE_DETECTED=false" >> "$GITHUB_ENV"
    fi
    exit 0
fi

echo "Update needed: $CURRENT_VERSION -> $LATEST_VERSION"

if [ -n "${GITHUB_ENV:-}" ]; then
    echo "UPDATE_DETECTED=true" >> "$GITHUB_ENV"
    echo "LATEST_VERSION=$LATEST_VERSION" >> "$GITHUB_ENV"
fi

get_hash() {
  local url="$1"
  echo "Prefetching $url..." >&2
  nix-prefetch-url --type sha256 "$url" | xargs nix hash to-sri --type sha256
}

# Base URL for downloads
BASE_URL="https://github.com/brave/brave-browser/releases/download/v${LATEST_VERSION}"
ASSET_NAME="brave-origin-nightly_${LATEST_VERSION}_amd64.deb"

# Fetch hash for x86_64-linux
HASH_AMD64=$(get_hash "$BASE_URL/$ASSET_NAME")

# Generate default.nix
cat > "$PACKAGE_FILE" << EOF
# Expression generated by update.sh; do not edit it by hand!
{ stdenv, callPackage, ... }@args:

let
  pname = "brave-origin";
  version = "${LATEST_VERSION}";

  allArchives = {
    x86_64-linux = {
      url = "https://github.com/brave/brave-browser/releases/download/v\${version}/brave-origin-nightly_\${version}_amd64.deb";
      hash = "${HASH_AMD64}";
    };
  };

in
callPackage ./make-brave.nix (removeAttrs args [ "callPackage" ]) {
  inherit pname version;
  archives = allArchives;
}
EOF

echo "Brave Origin updated to $LATEST_VERSION"
